name: Internal Continuous Integration
on: [pull_request]

jobs:
  tests:
    runs-on: self-hosted
    steps:
      #- run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@2020-q4
      - uses: actions/checkout@v2
      - run: make -j32 MODEL=n0100 epsilon.dfu test.elf
      - run: make -j32 epsilon.dfu test.elf
      - run: make -j32 PLATFORM=simulator epsilon.bin test.bin
      - run: output/release/simulator/linux/test.bin --headless --limit-stack-usage
